### ISSUE TITLE
error in display_image_predictions function

### ISSUE THREAD

**Issue by Mrmoore98** [deep-diver/CIFAR10-img-classification#1]
hi 
when I run your programme in  jupyter notebook it shows the following error "shape mismatch: objects cannot be broadcast to a single shape" in  "axies[image_i][1].barh(ind + margin, pred_values[::-1], width)" i merely running your file and change nothing

**Comment by Atrin4000** [comment]
Hello,

when I run it, it shows me  " NameError: name 'helper' is not defined" . Is there any file that I have download separately?

**Comment by deep-diver** [comment]
helper module was used in my testing time. I have removed all the helper things from the notebook recently. Please re-synch the file and re-run the notebook. Sorry for the inconvenience.

**Comment by deep-diver** [comment]
@Mrmoore98 

please let me know which part of the notebook you have changed

**Comment by Mrmoore98** [comment]
thanks and your programme help me a lot
