### ISSUE TITLE
Matplotlib error in test_model()

### ISSUE THREAD

**Issue by panovr** [deep-diver/CIFAR10-img-classification#5]
In test_model():

INFO:tensorflow:Restoring parameters from ./image_classification
Testing Accuracy: 0.7323845541401274

Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x7f1255652f28> (for post_execute):
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/lib/python3/dist-packages/matplotlib/pyplot.py in post_execute()
    148             def post_execute():
    149                 if matplotlib.is_interactive():
--> 150                     draw_all()
    151 
    152             # IPython >= 2

/usr/lib/python3/dist-packages/matplotlib/_pylab_helpers.py in draw_all(cls, force)
    148         for f_mgr in cls.get_all_fig_managers():
    149             if force or f_mgr.canvas.figure.stale:
--> 150                 f_mgr.canvas.draw_idle()
    151 
    152 atexit.register(Gcf.destroy_all)

/usr/lib/python3/dist-packages/matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   2059         if not self._is_idle_drawing:
   2060             with self._idle_draw_cntx():
-> 2061                 self.draw(*args, **kwargs)
   2062 
   2063     def draw_cursor(self, event):

/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py in draw(self)
    428             if toolbar:
    429                 toolbar.set_cursor(cursors.WAIT)
--> 430             self.figure.draw(self.renderer)
    431         finally:
    432             if toolbar:

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/usr/lib/python3/dist-packages/matplotlib/figure.py in draw(self, renderer)
   1297 
   1298             mimage._draw_list_compositing_images(
-> 1299                 renderer, self, artists, self.suppressComposite)
   1300 
   1301             renderer.close_group('figure')

/usr/lib/python3/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2435             renderer.stop_rasterizing()
   2436 
-> 2437         mimage._draw_list_compositing_images(renderer, self, artists)
   2438 
   2439         renderer.close_group('axes')

/usr/lib/python3/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

/usr/lib/python3/dist-packages/matplotlib/image.py in draw(self, renderer, *args, **kwargs)
    553         else:
    554             im, l, b, trans = self.make_image(
--> 555                 renderer, renderer.get_image_magnification())
    556             if im is not None:
    557                 renderer.draw_image(gc, l, b, im)

/usr/lib/python3/dist-packages/matplotlib/image.py in make_image(self, renderer, magnification, unsampled)
    780         return self._make_image(
    781             self._A, bbox, transformed_bbox, se

**Comment by deep-diver** [comment]
I am not aware of this error.

Can you share the system spec that you used?

**Comment by panovr** [comment]
TensorFlow 1.12.0
Python 3.6.7
Matplotlib 2.1.1

Is this a matplotlib version problem?

**Comment by deep-diver** [comment]
I am not sure, but possible. Did you find any solution yet?

**Comment by panovr** [comment]
upgrade matplotlib solve this issue.
